"""Auto-generated wiki index pages: by journal, by year, and by topic.

Topic (concept) pages are curated by hand / deep-writer; the topics index only
reflects them. The journal and year indexes come straight from the database.
All three files are fully regenerated on each run.
"""

from __future__ import annotations

import re
from pathlib import Path

HEADER = "<!-- AUTO-GENERATED by cite-hustle wiki-index; do not edit. -->\n\n"


def generate_indexes(pages, wiki_dir: Path) -> list[Path]:
    """Regenerate all index pages. `pages` is the get_ingested_wiki_pages frame."""
    index_dir = wiki_dir / "indexes"
    index_dir.mkdir(parents=True, exist_ok=True)

    written = [
        _write_by_journal(pages, index_dir),
        _write_by_year(pages, index_dir),
        _write_topics(pages, wiki_dir, index_dir),
    ]
    return written


def _entry_line(row) -> str:
    flag = " ⚑" if row["status"] == "flagged" else ""
    return (
        f"- [{row['title']}](../sources/{row['bib_key']}.md) "
        f"({row['authors']}, {row['year']}){flag}\n"
    )


def _write_by_journal(pages, index_dir: Path) -> Path:
    lines = [HEADER, "# Papers by journal\n\n"]
    if pages.empty:
        lines.append("_No papers ingested yet._\n")
    for journal, group in pages.groupby("journal_name", sort=True):
        lines.append(f"## {journal}\n\n")
        for _, row in group.sort_values(["year", "title"], ascending=[False, True]).iterrows():
            lines.append(_entry_line(row))
        lines.append("\n")
    path = index_dir / "by-journal.md"
    path.write_text("".join(lines), encoding="utf-8")
    return path


def _write_by_year(pages, index_dir: Path) -> Path:
    lines = [HEADER, "# Papers by year\n\n"]
    if pages.empty:
        lines.append("_No papers ingested yet._\n")
    for year, group in sorted(pages.groupby("year"), key=lambda kv: kv[0], reverse=True):
        lines.append(f"## {year}\n\n")
        for _, row in group.sort_values(["journal_name", "title"]).iterrows():
            lines.append(_entry_line(row))
        lines.append("\n")
    path = index_dir / "by-year.md"
    path.write_text("".join(lines), encoding="utf-8")
    return path


def _write_topics(pages, wiki_dir: Path, index_dir: Path) -> Path:
    """Topics index: every concept page plus the source pages it references."""
    concepts_dir = wiki_dir / "concepts"
    all_keys = set(pages["bib_key"]) if not pages.empty else set()
    referenced: set[str] = set()

    lines = [HEADER, "# Papers by topic\n\n"]
    concept_files = sorted(concepts_dir.glob("*.md")) if concepts_dir.exists() else []
    if not concept_files:
        lines.append(
            "_No concept pages yet. Create them under wiki/concepts/ "
            "(e.g. via deep-writer) and re-run `cite-hustle wiki-index`._\n\n"
        )

    for concept_path in concept_files:
        content = concept_path.read_text(encoding="utf-8", errors="replace")
        title_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
        title = title_match.group(1).strip() if title_match else concept_path.stem
        lines.append(f"## [{title}](../concepts/{concept_path.name})\n\n")

        linked = sorted(set(re.findall(r"sources/([a-z0-9]+)\.md", content)) & all_keys)
        referenced.update(linked)
        if linked:
            keyed = pages.set_index("bib_key")
            for key in linked:
                row = keyed.loc[key]
                lines.append(
                    f"- [{row['title']}](../sources/{key}.md) ({row['authors']}, {row['year']})\n"
                )
        else:
            lines.append("_No ingested sources linked yet._\n")
        lines.append("\n")

    unclassified = pages[~pages["bib_key"].isin(referenced)] if not pages.empty else pages
    if not unclassified.empty:
        lines.append("## Unclassified\n\n")
        lines.append("_Ingested but not yet linked from any concept page._\n\n")
        for _, row in unclassified.sort_values(
            ["year", "title"], ascending=[False, True]
        ).iterrows():
            lines.append(_entry_line(row))

    path = index_dir / "topics.md"
    path.write_text("".join(lines), encoding="utf-8")
    return path
